FashionPlatform.WebUI/Controllers/AdminController.cs
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity;
using System.Threading.Tasks;
using FashionPlatform.Domain.UserAndRole;
using FashionPlatform.Domain.UserAndRole.Infrastructure;
using FashionPlatform.WebUI.Models;

namespace FashionPlatform.WebUI.Controllers
{
    [Authorize(Roles = "Administrators")]
    public class AdminController : Controller
    {
        public ActionResult Index()
        {
            return View(UserManager.Users);
        }
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(RegisterUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                AppUser user = new AppUser { UserName = model.UserName,FirstName =model.FirstName, LastName = model.LastName,Email = model.Email};
                IdentityResult result =
                    await UserManager.CreateAsync(user, model.Password);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    AddErrorsFromResult(result);
                }
            }
            return View(model);
        }

        public async Task<ActionResult> Edit(string id)
        {
            AppUser user = await UserManager.FindByIdAsync(id);
            if (user != null)
            {
                return View(user);
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public async Task<ActionResult> Edit(string id, string email, string password)
        {
            AppUser user = await UserManager.FindByIdAsync(id);
            if (user != null)
            {
                user.Email = email;
                IdentityResult validEmail
                    = await UserManager.UserValidator.ValidateAsync(user);

                if (!validEmail.Succeeded)
                {
                    AddErrorsFromResult(validEmail);
                }

                IdentityResult validPass = null;
                if (password != string.Empty)
                {
                    validPass
                        = await UserManager.PasswordValidator.ValidateAsync(password);

                    if (validPass.Succeeded)
                    {
                        user.PasswordHash =
                            UserManager.PasswordHasher.HashPassword(password);
                    }
                    else
                    {
                        AddErrorsFromResult(validPass);
                    }
                }

                if ((validEmail.Succeeded && validPass == null) ||
                        (validEmail.Succeeded && password != string.Empty && validPass.Succeeded))
                {
                    IdentityResult result = await UserManager.UpdateAsync(user);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        AddErrorsFromResult(result);
                    }
                }
            }
            else
            {
                ModelState.AddModelError("", "Пользователь не найден");
            }
            return View(user);
        }


        [HttpPost]
        public async Task<ActionResult> Delete(string id)
        {
            AppUser user = await UserManager.FindByIdAsync(id);

            if (user != null)
            {
                IdentityResult result = await UserManager.DeleteAsync(user);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return View("Error", result.Errors);
                }
            }
            else
            {
                return View("Error", new string[] { "Пользователь не найден" });
            }
        }

        private void AddErrorsFromResult(IdentityResult result)
        {
            foreach (string error in result.Errors)
            {
                ModelState.AddModelError("", error);
            }
        }

        private AppUserManager UserManager
        {
            get { return HttpContext.GetOwinContext().GetUserManager<AppUserManager>(); }
        }
    }
}

FashionPlatform.WebUI/Controllers/ProductController.cs
using System.Linq;
using System.Web.Mvc;
using FashionPlatform.Domain.Abstract;
using FashionPlatform.Domain.Entities;
using FashionPlatform.WebUI.Models;

namespace FashionPlatform.WebUI.Controllers
{
    public class ProductController : Controller
    {
        private IProductRepository repository;

        public ProductController(IProductRepository repo)
        {
            repository = repo;
        }

        public int pageSize = 3;

        // GET: Product
        public ViewResult List(string category, int page = 1)
        {
            ProductsListViewModel model = new ProductsListViewModel  // Передаем всю нужную информацью в представление через данный обьект 
            {
                Products = repository.Products // Сортировка продуктов и отоброжение их на странице в количестве PageSize
                    .Where(p => category == null || p.Category == category)
                    .OrderBy(p => p.ProductId)
                    .Skip((page - 1) * pageSize)// В зависимости на какой мы странице пропускаем продукты
                    .Take(pageSize), // Выбираем количество продуктов равных PageSize
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    TotalItems = repository.Products.Count(p => category==null||p.Category==category)
                },
                CurrentCategory = category
            };
            return View(model);
        }

        public FileContentResult GetImage(int productId)
        {
            Product product = repository.Products.FirstOrDefault(p => p.ProductId == productId);
            if (product != null)
            {
                return File(product.ImageData, product.ImageMimeType);
            }
            else
            {
                return null;
            }
        }
    }
}

FashionPlatform.WebUI/Views/oldAdmin/Edit.cshtml
@using FashionPlatform.Domain.Entities
@model FashionPlatform.Domain.Entities.Product

@{
    ViewBag.Title = "Admin Panel. Edit Product";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<div class="panel">
    <div class="panel-heading">
        <h2>Edit Product: @Model.Name</h2>
    </div>
</div>
@using (Html.BeginForm("Edit", "Admin", FormMethod.Post, new {enctype= "multipart/form-data" }))
{
    <div class="panel-body">
        @Html.HiddenFor(p => p.ProductId)
        @foreach (var item in ViewData.ModelMetadata.Properties)
        {
            switch (item.PropertyName)
            {
                case "ProductId":
                case "ImageData":
                case "ImageMimeType":
                    break;
                default:
                    <div class="panel-group">
                        <lable>@(item.DisplayName ?? item.PropertyName)</lable>
                        @if (item.PropertyName == "Description")
                        {
                            @Html.TextArea(item.PropertyName, null, new { @class = "form-control", rows = 5 })
                        }
                        else
                        {
                            @Html.TextBox(item.PropertyName, null, new { @class = "form-control" })
                        }
                        @Html.ValidationMessage(item.PropertyName)
                    </div>
                    break;
            }
        }
        <div class="form-group">
            <div style="position: relative">
                <label>Image</label>
                <a class="btn" href='javascript:;'>
                    Choose file
                    <input type="file" name="Image" size="40"
                           style="position: absolute; z-index:2;top:0;left:0;filter: alpha(opacity=0); opacity:0;
                                                                                                  background-color:transparent;color:transparent;"
                           onchange='$("#upload-file-info").html($(this).val());' />
                </a>
                <span class='label label-info' id="upload-file-info"></span>
                <div>
                    @if (Model.ImageData == null)
                    {
                        <div class="form-control-static">Not Image</div>
                    }
                    else
                    {
                        <img class="thumbnail" height="150" width="150"
                        src="@Url.Action("GetImage", "Product", new { Model.ProductId })"/>
                    }
                </div>
            </div>
        </div>

        <div class="panel-footer">
            <input type="submit" class="btn btn-primary" value="Save" />
            @Html.ActionLink("Don't save and return to list of product!", "Index", null, new { @class = "btn btn-default" })
        </div>
    </div>
}

FashionPlatform.WebUI/Views/oldAdmin/Index.cshtml
@model IEnumerable<FashionPlatform.Domain.Entities.Product>

@{
    ViewBag.Title = "Admin Panel. List of Product";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="panel panel-default">
    <div class="panel-heading">
        <h3>List of product</h3>
    </div>
    <div class="panel-body">
        <table class="table table-striped table-condensed table-bordered">
            <tr>
                <th class="text-right">ID</th>
                <th>Name</th>
                <th class="text-right">Price</th>
                <th class="text-center">Action</th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td class="text-right">@item.ProductId</td>
                    <td>@Html.ActionLink(item.Name, "Edit", new {item.ProductId})</td>
                    <td class="text-right">@item.Price.ToString("# $")</td>
                    <td class="text-center">
                        @using (Html.BeginForm("Delete", "Admin"))
                        {
                            @Html.Hidden("ProductId", item.ProductId)
                            <input type="submit" class="btn btn-default btn-xs" value="Delete"/>
                        }
                    </td>
                </tr>
            }
        </table>
    </div>
    <div class="panel-footer">
        @Html.ActionLink("Create Item", "Create", null, new {@class="btn btn-default"})
    </div>
</div>