FashionPlatform.WebUI/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using FashionPlatform.Domain.Abstract;
using FashionPlatform.Domain.Entities;
using FashionPlatform.WebUI.Models;

namespace FashionPlatform.WebUI.Controllers
{
    public class CartController : Controller
    {
        private IProductRepository repository;
        private IOrderProcessor orderProcessor;

        public CartController(IProductRepository repo, IOrderProcessor processor)
        {
            repository = repo;
            orderProcessor = processor;

        }

        public ViewResult Index(Cart cart, string returnUrl)
        {
            return View(new CartIndexViewModels
            {
                Cart = cart,
                ReturnUrl = returnUrl
            });
        }
        public RedirectToRouteResult AddToCart(Cart cart, int productID, string returnUrl)//Добавление продукта в корзину 
        {
            Product product = (Product)repository.Products.Where(p => p.ProductId == productID).FirstOrDefault();
            if (product != null)
            {
                cart.Add(product, 1);
            }
            return RedirectToAction("Index", new { returnUrl });// В представление передаем ссылкы откуда мы попали в корзину
        }

        public RedirectToRouteResult RemoveFromCart(Cart cart, int productID, string returnUrl) // Удаление продукта из корзины
        {
            Product product = (Product)repository.Products.Where(p => p.ProductId == productID).FirstOrDefault();
            if (product != null)
            {
                cart.RemoveLine(product);
            }
            return RedirectToAction("Index", new { returnUrl });// В представление передаем ссылкы откуда мы попали в корзину
        }

        public PartialViewResult Summary(Cart cart)
        {
            return PartialView(cart);
        }

        public ViewResult Checkout()
        {
            return View(new ShippingDetails());
        }
        [HttpPost]
        public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Your cart is empty!");
            }
            if (ModelState.IsValid)
            {
                orderProcessor.ProcessOrder(cart, shippingDetails);
                cart.Clear();
                return View("Completed");
            }
            else
            {
                return View(shippingDetails);
            }
        }
    }
}

FashionPlatform.WebUI/Controllers/ProductController.cs
using System.Linq;
using System.Web.Mvc;
using FashionPlatform.Domain.Abstract;
using FashionPlatform.Domain.Entities;
using FashionPlatform.WebUI.Models;

namespace FashionPlatform.WebUI.Controllers
{
    public class ProductController : Controller
    {
        private IProductRepository repository;

        public ProductController(IProductRepository repo)
        {
            repository = repo;
        }

        public int pageSize = 3;

        // GET: Product
        public ViewResult List(string category, int page = 1)
        {
            ProductsListViewModel model = new ProductsListViewModel  // Передаем всю нужную информацью в представление через данный обьект 
            {
                Products = repository.Products // Сортировка продуктов и отоброжение их на странице в количестве PageSize
                    .Where(p => category == null || p.Category == category)
                    .OrderBy(p => p.ProductId)
                    .Skip((page - 1) * pageSize)// В зависимости на какой мы странице пропускаем продукты
                    .Take(pageSize), // Выбираем количество продуктов равных PageSize
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = pageSize,
                    TotalItems = repository.Products.Count(p => category==null||p.Category==category)
                },
                CurrentCategory = category
            };
            return View(model);
        }

        public FileContentResult GetImage(int productId)
        {
            Product product = repository.Products.FirstOrDefault(p => p.ProductId == productId);
            if (product != null)
            {
                return File(product.ImageData, product.ImageMimeType);
            }
            else
            {
                return null;
            }
        }
    }
}

FashionPlatform.WebUI/Controllers/SellerController.cs
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Web;
using System.Web.Mvc;
using FashionPlatform.Domain.Abstract;
using FashionPlatform.Domain.Concrete;
using FashionPlatform.Domain.Entities;
using FashionPlatform.WebUI.Models;

namespace FashionPlatform.WebUI.Controllers
{
    public class SellerController : Controller
    {
        private IProductRepository repository;

        public SellerController(IProductRepository repo)
        {
            repository = repo;
        }
        // GET: Admin
        public ViewResult Index()
        {
            return View(repository.Products);
        }

        public ViewResult Edit(int productId)
        {
            Product p = repository.Products.FirstOrDefault(m => m.ProductId == productId)??new Product(); // получаем продукт который будет модифицирован
            ProductViewModel productViewModel = new ProductViewModel // Создаем экземпляр класса для передачи для передачи данных в наше представление
            {
                Category = p.Category,
                Description = p.Description,
                ImageData = p.ImageData,
                ImageMimeType = p.ImageMimeType,
                ProductId = p.ProductId,
                Price = p.Price,
                Name = p.Name,
                CountryId = p.CountryId,
                CountryName = repository.Countries.FirstOrDefault(s => s.CountryId == p.CountryId)?.CountryName,
                ShoeId = p.ShoeId,
                ShoeName = repository.Shoes.FirstOrDefault(s => s.ShoeId == p.ShoeId)?.ShoeName,
                UpWearId = p.UpWearId,
                UpWearName = repository.UpWears.FirstOrDefault(s => s.UpWearId == p.UpWearId)?.UpWearName,
                DownWearId = p.DownWearId,
                DownWearName = repository.DownWears.FirstOrDefault(s => s.DownWearId == p.DownWearId)?.DownWearName,
                DressCodeId = p.DressCodeId,
                DressCodeName = repository.DressCodes.FirstOrDefault(s => s.DressCodeId == p.DressCodeId)?.DressCodeName,
                FiberId = p.FiberId,
                FiberName = repository.Fibers.FirstOrDefault(s => s.FiberId == p.FiberId)?.FiberName,
                ProductDestinationId = p.ProductDestinationId,
                ProductDestinationName = repository.ProductDestinasions.FirstOrDefault(s => s.ProductDestinationId == p.ProductDestinationId)?.ProductDestinationName,
                StyleId = p.StyleId,
                StyleName = repository.Styles.FirstOrDefault(s => s.StyleId == p.StyleId)?.StyleName,
                AccessoryId = p.AccessoryId,
                AccessoryName = repository.Accessories.FirstOrDefault(s => s.AccessoryId == p.AccessoryId)?.AccessoryName,
                ClothId = p.ClothId,
                ClothName = repository.Clothes.FirstOrDefault(s => s.ClothId == p.ClothId)?.ClothName

            };
            List<Shoe> listShoes = repository.Shoes.ToList();                       //Создаем списки для елементов DropDownList
            List<Accessory> listAccessories = repository.Accessories.ToList();
            List<Country> listCountries = repository.Countries.ToList();
            var listClothes = (from cloth in repository.Clothes                     // Список элементов сгрупированных по типу волокна
                               join type in repository.TypesCloths on cloth.TypeClothId equals type.TypeClothId
                               select new
                               {
                                   ClothName = cloth.ClothName,
                                   ClothId = cloth.ClothId,
                                   typeCloth = type.TypeClothName
                               }).ToList();
            List<DownWear> listDownWears = repository.DownWears.ToList();
            List<UpWear> listUpWears = repository.UpWears.ToList();
            List<DressCode> listDressCodes = repository.DressCodes.ToList();
            var listFibers = (from fib in repository.Fibers
                              join type in repository.TypesFibers on fib.TypeFiberId equals type.TypeFiberId
                              select new
                              {
                                  FiberName = fib.FiberName,
                                  FiberId = fib.FiberId,
                                  typeFiber = type.TypeFiberName
                              }).ToList();
            List<ProductDestination> listProductDestinations = repository.ProductDestinasions.ToList();
            List<Style> listStyles = repository.Styles.ToList();


            ViewBag.Shoes = new SelectList(listShoes, "ShoeId", "ShoeName");
            ViewBag.Accessories = new SelectList(listAccessories, "AccessoryId", "AccessoryName");
            ViewBag.Clothes = new SelectList(listClothes, "ClothId", "ClothName", "typeCloth", productViewModel.ClothId);
            ViewBag.Countries = new SelectList(listCountries, "CountryId", "CountryName");
            ViewBag.DownWears = new SelectList(listDownWears, "DownWearId", "DownWearName");
            ViewBag.UpWears = new SelectList(listUpWears, "UpWearId", "UpWearName");
            ViewBag.DressCodes = new SelectList(listDressCodes, "DressCodeId", "DressCodeName");
            ViewBag.Fibers = new SelectList(listFibers, "FiberId", "FiberName", "typeFiber", productViewModel.FiberId);
            ViewBag.ProductDestinations = new SelectList(listProductDestinations, "ProductDestinationId", "ProductDestinationName");
            ViewBag.Styles = new SelectList(listStyles, "StyleId", "StyleName");
            return View(productViewModel);
        }

        [HttpPost]
        public ActionResult Edit(ProductViewModel productViewModel, HttpPostedFileBase image = null)
        {
            if (ModelState.IsValid)
            {
                Product product = new Product
                {
                    ProductId = productViewModel.ProductId,
                    Name = productViewModel.Name,
                    Description = productViewModel.Description,
                    Category = productViewModel.Category,
                    Price = productViewModel.Price,
                    ClothId = productViewModel.ClothId,
                    CountryId = productViewModel.CountryId,
                    DressCodeId = productViewModel.DressCodeId,
                    ShoeId = productViewModel.ShoeId,
                    StyleId = productViewModel.StyleId,
                    UpWearId = productViewModel.UpWearId,
                    DownWearId = productViewModel.DownWearId,
                    ProductDestinationId = productViewModel.ProductDestinationId,
                    FiberId = productViewModel.FiberId,
                    AccessoryId = productViewModel.AccessoryId
                };
                if (image != null)
                {
                    product.ImageMimeType = image.ContentType;
                    product.ImageData = new byte[image.ContentLength];
                    image.InputStream.Read(product.ImageData, 0, image.ContentLength);
                }
                repository.SaveProduct(product);
                TempData["message"] = $"Change saved in product: {product.Name}.";
                return RedirectToAction("Index");
            }
            else
            {
                return View(productViewModel);
            }

        }

        public ActionResult Create()
        {
            return RedirectToAction("Edit", new ProductViewModel());
        }

        [HttpPost]
        public ActionResult Delete(int productId)
        {
            Product deletedProduct = repository.DeleteProduct(productId);
            if (deletedProduct != null)
            {
                TempData["message"] = $"Product {deletedProduct.Name} was deleted";
            }
            return RedirectToAction("Index");
        }
    }
}

FashionPlatform.WebUI/Views/Shared/MenuForSellers.cshtml
<li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
    <ul class="dropdown-menu">
        <li><a href=@Url.Action("Index", "Seller")>Товары</a></li>
        <li><a href="#">Личный кабинет</a></li>
        <li role="separator" class="divider"></li>
        <li><a href=@Url.Action("Logout", "Account")>Выход</a></li>
    </ul>
</li>

FashionPlatform.WebUI/Views/Shared/ProductSummary.cshtml
@model FashionPlatform.Domain.Entities.Product
<!--
Частичное представление для визуализаций продукта и его характеристику
    -->
<div class="well">
    @if (Model.ImageData != null)
    {
        <div class="pull-left" style="margin-right: 10px">
            <img class="img-thumbnail" width="75" height="75"
                 src="@Url.Action("GetImage", "Product",
                          new { Model.ProductId })" />
        </div>
    }
    <h3>
        <strong>@Model.Name</strong>
        <span class="pull-right label label-primary">@Model.Price.ToString("# $")</span>
    </h3>
    @using (Html.BeginForm("AddToCart", "Cart"))
    {
        <div class="pull-right">
            @Html.HiddenFor(x => x.ProductId)
            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
            <input type="submit" class="btn btn-success" value="Добавить в корзину"/>
        </div>
    }

    <span class="lead">@Model.Description</span>
</div>

FashionPlatform.WebUI/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyle.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <title></title>

    <title>@ViewBag.Title</title>
</head>
<body>
<div>
    @if (TempData["message"] != null)
    {
        <div class="alert alert-success">@TempData["message"]</div>
    }
    @RenderBody()
</div>
</body>
</html>

FashionPlatform.WebUI/Views/Shared/_Layout.cshtml
@using System.EnterpriseServices.CompensatingResourceManager
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/ErrorStyle.css" rel="stylesheet" />
    <link href="~/Content/carousel.css" rel="stylesheet">
    <script type="text/javascript" src="~/scripts/jquery-1.10.2.js"></script>
    <script type="text/javascript" src="~/scripts/bootstrap.min.js"></script>
    <title>@ViewBag.Title</title>
</head>
<body>
    <div class="navbar-wrapper">
        @if (TempData["message"] != null)
        {
            <div class="alert alert-success">@TempData["message"]</div>
        }
        <div class="container">

            <div class="navbar navbar-inverse navbar-static-top" role="navigation">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href=@Url.Action("List", "Product")>Shopping</a>
                    </div>
                    <div class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                            <li class="active"><a href="#">Home</a></li>
                            <li><a href="#about">About</a></li>
                            <li><a href="#contact">Contact</a></li>
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
                                <ul class="dropdown-menu">
                                    <li><a href="#">Action</a></li>
                                    <li><a href="#">Another action</a></li>
                                    <li><a href="#">Something else here</a></li>
                                    <li class="divider"></li>
                                    <li class="dropdown-header">Nav header</li>
                                    <li><a href="#">Separated link</a></li>
                                    <li><a href="#">One more separated link</a></li>
                                </ul>
                            </li>
                        </ul>
                        <ul class="nav navbar-nav navbar-right">
                            @if (HttpContext.Current.User.IsInRole("Administrators"))
                            {
                                <li>@Html.ActionLink("Log Out", "Logout", "Account")</li>
                            }
                            else if (HttpContext.Current.User.IsInRole("Sellers"))
                            {
                                @Html.Partial("MenuForSellers")
                            }
                            else if (HttpContext.Current.User.IsInRole("Users"))
                            {
                                <li> @Html.Action("Summary", "Cart")</li>
                                <li>@Html.ActionLink("Log Out", "Logout", "Account")</li>
                            }
                            else
                            {
                                <li>@Html.ActionLink("Sign In", "Login", "Account")</li>
                                <li>@Html.ActionLink("Sign Up", "Register", "Account")</li>

                            }
                        </ul>
                    </div>
                </div>
            </div>
            @RenderBody()
        </div>
    </div>
</body>
</html>